### ISSUE TITLE
Subject: Issue Report - Uncaught ReferenceError when Deleting Items from Cart

### ISSUE THREAD

**Issue by adarshdhital007** [dejwid/food-ordering#1]
Description:
Upon visiting the website at https://dawid-food-ordering-app.vercel.app/, 
I encountered an issue while attempting to delete items from the shopping cart. The following error message was displayed: "Uncaught ReferenceError: index is not defined."

Steps to Reproduce:

Navigate to the provided website: https://dawid-food-ordering-app.vercel.app/.
Add items to the shopping cart.
Attempt to delete an item from the cart.

Expected Behavior:
I expected to be able to remove items from the shopping cart without encountering any errors.

Actual Behavior:
The deletion attempt resulted in the following error: "Uncaught ReferenceError: index is not defined."

**Comment by imrushikesh77** [comment]
Hey, can I work on this issue?
